Allow passing in `$popertyId` dynamically
gtmassey/laravel-analytics pull request #52
Opened 2023-01-19 15:01 UTC by alexacron

The optional parameter $propertyId allows bypassing the configured parameter. This allows adding properties via API then using them here. Useful for cross-domain tracking also.

2023-01-22 21:15 UTC, Plytas commented
Thanks for the contribution @alexacron. Would you mind writing tests for this?

2023-02-23 15:30 UTC, Plytas requested changes
@alexacron couple of syntactic changes, but otherwise looks good!

2023-02-23 15:30 UTC, Plytas commented on src/Analytics.php
> +        }
```suggestion
        $propertyId ??= config('analytics.property_id');
```

2023-02-23 15:30 UTC, Plytas commented on src/Analytics.php
> +    public static function query(?string $propertyId=null): static
```suggestion
    public static function query(?string $propertyId = null): static
```

2023-02-23 15:30 UTC, Plytas commented
@gtmassey Could you look into failing pint action?

2023-02-24 08:51 UTC, alexacron reviewed
I've run pint locally and committed the changes. I don't know why they fail on remote on the same files I just fixed.

2023-02-24 09:15 UTC, Plytas commented
It's the commit step of the action that fails due to permission issue.

2023-02-24 09:19 UTC, alexacron commented
> It's the commit step of the action that fails due to permission issue.

Anything I can do ?

2023-02-24 09:29 UTC, Plytas commented
@alexacron would you mind giving me write permission to your fork? Without it I cannot push changes to this PR. I want to bump composer dev dependencies and also bump Pint action version so it can use newest Pint. For some reason the old version still picks up changes even though you already committed them.

2023-02-24 09:36 UTC, alexacron commented
I sent you an invitation

2023-02-24 10:43 UTC, Plytas approved these changes

2023-02-24 10:47 UTC, merged